package edu.bit.cs;

public enum BUG_TYPE {
    NULL_POINTER_EXEPTION,
    RESOURCE_LEAK,
    INJECTION,
    BROKEN_AUTHENTICATION,
    SENSITIVE_DATA_EXPOSURE,
    XML_EXTERNAL_ENTITIES,
    BROKEN_ACCESS_CONTROL,
    SAFETY_MISCONFIGURATION,
    CROSS_SITE_SCRIPTING,
    INSECURE_DESERIALIZATION,
    ANOTHER_TYPE
}
